title: Convolutional Dynamic Alignment Networks
subtitle: for interpretable classifications
authors: M. Böhle, M. Fritz, B. Schiele
description: >- # this means to ignore newlines until "baseurl:"
  CVPR 2021 Oral

# Build settings
theme: jekyll-theme-slate
