title: Convolutional Dynamic Alignment Networks
subtitle: for interpretable classifications
authors: Moritz Böhle, Mario Fritz, Bernt Schiele
description: >- # this means to ignore newlines until "baseurl:"
  CVPR 2021 Oral

# Build settings
theme: jekyll-theme-slate
